# Generated by Django 4.1.4 on 2022-12-29 00:05

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': '사회자태그',
                'verbose_name_plural': '사회자태그',
            },
        ),
        migrations.AlterModelOptions(
            name='backdrops',
            options={'verbose_name': '배경', 'verbose_name_plural': '배경'},
        ),
        migrations.AlterModelOptions(
            name='mc',
            options={'verbose_name': '사회자', 'verbose_name_plural': '사회자'},
        ),
        migrations.CreateModel(
            name='TaggedMc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='wedding.mctag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mc',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='wedding.TaggedMc', to='wedding.McTag', verbose_name='Tags'),
        ),
    ]
