# Generated by Django 4.1.4 on 2023-01-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_mctag_alter_backdrops_options_alter_mc_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': '_문의', 'verbose_name_plural': '_문의'},
        ),
    ]
